src/Entity/Comments.php
<?php

namespace App\Entity;

use App\Entity\Trait\CreatedAtTrait;
use App\Entity\Trait\UpdatedAtTrait;
use App\Repository\CommentsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentsRepository::class)]
class Comments
{
    use CreatedAtTrait,UpdatedAtTrait;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $text = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $files = null;

    #[ORM\Column]
    private ?int $user_id = null;

    #[ORM\Column]
    private ?int $claims_id = null;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Claims", inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?Claims $claims;

    public function getClaims(): ?Claims
    {
        return $this->claims;
    }
    public function setClaims(?Claims $claims): self
    {
        $this->claims = $claims;
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(?string $text): static
    {
        $this->text = $text;
        return $this;
    }

    public function getFiles(): ?string
    {
        return $this->files;
    }

    public function setFiles(?string $files): static
    {
        $this->files = $files;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getClaimsId(): ?int
    {
        return $this->claims_id;
    }

    public function setClaimsId(int $claims_id): static
    {
        $this->claims_id = $claims_id;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->files;
    }

    public function setFile($files): static
    {
        $this->files = $files;
        return $this;
    }
}

src/Form/CommentsType.php
<?php

namespace App\Form;

use App\Entity\Comments;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('text')
            ->add('file', FileType::class, ['mapped' => false, 'required'=> false])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Comments::class,
        ]);
    }
}

src/Controller/CommentsController.php
<?php

namespace App\Controller;

use App\Entity\Claims;
use App\Entity\Comments;

use App\Form\CommentsType;
use App\Repository\CommentsRepository;
use App\Service\FileService;
use DateTimeImmutable;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/comments')]
class CommentsController extends AbstractController
{
    #[Route('/', name: 'app_comments_index', methods: ['GET'])]
    public function index(CommentsRepository $commentsRepository): Response
    {
        return $this->render('comments/index.html.twig', [
            'comments' => $commentsRepository->findAll(),
        ]);
    }

    #[Route('/new/{id}', name: 'app_comments_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CommentsRepository $commentsRepository, Claims $claims, FileService $fileService): Response
    {
        $comment = new Comments();
        $form = $this->createForm(CommentsType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form['file']->getData();
            if(!empty($file)){
                $path = $this->getParameter('kernel.project_dir')."/public/uploads/comments";
                $comment =  $fileService->saveFile($comment, $file, $path);
            }
            $comment->setUserId(1);
            $comment->setClaimsId($claims->getId());
            $dateTimeNow = new DateTimeImmutable();
            $comment->setCreatedAt($dateTimeNow);
            $comment->setUpdatedAt($dateTimeNow);
            $commentsRepository->save($comment, true);

            return $this->redirectToRoute('app_claims_show', ['id'=>$claims->getId()], Response::HTTP_SEE_OTHER);
        } else {
            return $this->render('comments/new.html.twig', array(
                'form' => $form->createView(),
            ));
        }
    }

    #[Route('/{id}', name: 'app_comments_show', methods: ['GET'])]
    public function show(Comments $comment, CommentsRepository $commentsRepository): Response
    {
        $comment = $commentsRepository->getCommentUserById($comment->getId());
        return $this->render('comments/show.html.twig', [
            'comment' => $comment,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_comments_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Comments $comment, CommentsRepository $commentsRepository, FileService $fileService): Response
    {
        $form = $this->createForm(CommentsType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form['file']->getData();
            if(!empty($file)){
                $path = $this->getParameter('kernel.project_dir')."/public/uploads/comments";
                $comment =  $fileService->saveFile($comment, $file, $path);
            }
            $comment->setUserId(1);
            $dateTimeNow = new DateTimeImmutable();
            $comment->setUpdatedAt($dateTimeNow);
            $commentsRepository->save($comment, true);
            return $this->redirectToRoute('app_claims_show', ['id'=>$comment->getClaimsId()], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('comments/edit.html.twig', [
            'comment' => $comment,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_comments_delete', methods: ['POST'])]
    public function delete(Request $request, Comments $comment, CommentsRepository $commentsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$comment->getId(), $request->request->get('_token'))) {
            $commentsRepository->remove($comment, true);
        }
        return $this->redirectToRoute('app_comments_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/comments/_delete_form.html.twig
<form method="post" action="{{ path('app_comments_delete', {'id': comment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comment.id) }}">
    <button class="btn">Delete</button>
</form>

templates/comments/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/comments/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Comments{% endblock %}

{% block body %}
    <h1>Edit Comments</h1>

    {{ include('comments/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_comments_index') }}">back to list</a>

    {{ include('comments/_delete_form.html.twig') }}
{% endblock %}

templates/comments/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comments index{% endblock %}

{% block body %}
    <h1>Comments index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Text</th>
                <th>Files</th>
                <th>User_id</th>
                <th>Claims_id</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for comment in comments %}
            <tr>
                <td>{{ comment.id }}</td>
                <td>{{ comment.text }}</td>
                <td>{{ comment.files }}</td>
                <td>{{ comment.userId }}</td>
                <td>{{ comment.claimsId }}</td>
                <td>
                    <a href="{{ path('app_comments_show', {'id': comment.id}) }}">show</a>
                    <a href="{{ path('app_comments_edit', {'id': comment.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/comments/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Comments{% endblock %}

{% block body %}
    <h1>Create new Comments</h1>

    {{ include('comments/_form.html.twig') }}

    <a href="{{ path('app_comments_index') }}">back to list</a>
{% endblock %}

templates/comments/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comments{% endblock %}

{% block body %}
    <h1>Comments</h1>
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ comment.id }}</td>
            </tr>
            <tr>
                <th>Text</th>
                <td>{{ comment.text }}</td>
            </tr>
            <tr>
                <th>Files</th>
                <td><img height="200" width="200" src="{{ asset('uploads/comments/')~comment.files }}" alt="file"/></td>
            </tr>
            <tr>
                <th>User_id</th>
                <td>{{ comment.user_name }}</td>
            </tr>
            <tr>
                <th>Claims_id</th>
                <td>{{ comment.claims_id }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_comments_index') }}">back to list</a>

    <a href="{{ path('app_comments_edit', {'id': comment.id}) }}">edit</a>

    {{ include('comments/_delete_form.html.twig') }}
{% endblock %}